export default [
  {
    id: 1,
    title: "Life Lessons with Katie Zaferes",
    description:
      'I will share with you what I call "Positively Impactful Moments of Disappointment." Throughout my career, many of my highest moments only came after setbacks and losses. But learning from those difficult moments is what gave me the ability to rise above them and reach my goals.',
    price: 136,
    coverImg: "katie-zaferes.png",
    stats: {
      rating: 5.0,
      reviewCount: 6,
    },
    location: "Online",
    openSpots: 0,
  },
  {
    id: 2,
    title: "Learn Wedding Photography",
    description:
      "Interested in becoming a wedding photographer? For beginner and experienced photographers alike, join us in learning techniques required to leave the happy couple with memories that'll last a lifetime.",
    price: 125,
    coverImg: "wedding-photography.png",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "Online",
    openSpots: 27,
  },
  {
    id: 3,
    title: "Group Mountain Biking",
    description:
      "Experience the beautiful Norwegian landscape and meet new friends all while conquering rugged terrain on your mountain bike. (Bike provided!)",
    price: 50,
    coverImg: "mountain-bike.png",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "Norway",
    openSpots: 3,
  },
  {
    id: 4,
    title: "Learn basics of acting from Jarmo Koski",
    description:
      "Learn basics of acting from Jarmo Koski, a Finnish famous Salatut Elämät actor",
    price: 299,
    coverImg: "seppochu.jpg",
    stats: {
      rating: 5,
      reviewCount: 262,
    },
    location: "Finland",
    openSpots: 0,
  },
  {
    id: 5,
    title: "Join the local airsoft group",
    description: "Bring your own airsoft guns and equipment",
    price: 10,
    coverImg: "airsoftpic.jpg",
    stats: {
      rating: 4,
      reviewCount: 48,
    },
    location: "Sweden",
    openSpots: 40,
  },
  {
    id: 6,
    title: "Downhill skiing course",
    description: "Own downhill skiing equipment or rented ones",
    price: 190,
    coverImg: "downhillskiing.jpg",
    stats: {
      rating: 4.9,
      reviewCount: 138,
    },
    location: "Chamonix, France",
    openSpots: 23,
  },
  {
    id: 7,
    title: "Learn how to train your dog",
    description: "Dog training",
    price: 45,
    coverImg: "dogs.jpg",
    stats: {
      rating: 3.7,
      reviewCount: 36,
    },
    location: "Online",
    openSpots: 12,
  },
  {
    id: 8,
    title: "Free coffee",
    description: "Come get some free coffee",
    price: 0,
    coverImg: "kahvi.jpg",
    stats: {
      rating: 5,
      reviewCount: 79,
    },
    location: "New York",
    openSpots: 5,
  },
  {
    id: 9,
    title: "Learn tennis with Pablo",
    description: "Awesome tennis training with Pablo",
    price: 400,
    coverImg: "tennispic.jpg",
    stats: {
      rating: 3.5,
      reviewCount: 15,
    },
    location: "Mijas, Spain",
    openSpots: 17,
  },
  {
    id: 10,
    title: "Come play golf!",
    description: "Supreme golfing in Marbella",
    price: 159,
    coverImg: "golfcart.jpg",
    stats: {
      rating: 4,
      reviewCount: 46,
    },
    location: "Marbella, Spain",
    openSpots: 28,
  },
];
